algoritmo "questao_3"

var
  n: caractere
inicio
      escreval("     BANCO DE DADOS     ")
      escreval("========================")
      escreval
      escreva("NOME DO FUNCIONÁRIO: ")
      leia(n)
      se (n="Maria do Carmo") entao
         escreval("O funcionário Maria do Carmo tem um salário de R$1850,45 em Junho")
      senao
           escreval("I didn't think that far")
      fimse
      escreval("***")
      
fimalgoritmo
